#!/usr/bin/env python

import sys

from assembly_gui_rqt_plugin.assembly_gui import AssemblyGuiPlugin
from rqt_gui.main import Main

plugin = 'assembly_gui_rqt_plugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
